name: Build Website

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: node --version
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: pnpm build && pnpm export
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=out --prod
